inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'gemfiles/vendor/**/*'

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FileName:
  Exclude:
    - 'activerecord-time.gemspec'
    - 'lib/activerecord-time.rb'

Style/FormatString:
  EnforcedStyle: percent

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true
