language: ruby
sudo: false
rvm:
  - 2.3.1
  - jruby-9.1.0.0
  - 2.2
  - jruby-9.0.5.0
  - 2.1
  - 2.0.0
  - jruby-1.7.25
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/ar42.gemfile
  - gemfiles/ar41.gemfile
  - gemfiles/ar40.gemfile
  - gemfiles/ar32.gemfile
env:
  - ADAPTER="postgresql"
  - ADAPTER="derby"
  - ADAPTER="sqlite3"
matrix:
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/ar40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ar32.gemfile
