language: ruby
sudo: false
jdk:
  - oraclejdk8
before_install: gem query -i -n ^bundler$ >/dev/null || gem install bundler
rvm:
  - ruby-2.3.3
  - jruby-9.1.6.0
  - ruby-2.2.6
  - ruby-2.1.9
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/ar50.gemfile
  - gemfiles/ar42.gemfile
  - gemfiles/ar41.gemfile
  - gemfiles/ar40.gemfile
  - gemfiles/ar32.gemfile
env:
  - JRUBY_OPTS="--dev --debug" ADAPTER="postgresql"
  - JRUBY_OPTS="--dev --debug" ADAPTER="derby"
  - JRUBY_OPTS="--dev --debug" ADAPTER="sqlite3"
matrix:
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/ar42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ar41.gemfile
    - rvm: ruby-2.1.9
      gemfile: gemfiles/ar50.gemfile
