language: ruby
sudo: false
rvm:
  - jruby-head
  - ruby-head
  - jruby-9.0.0.0
  - "2.2"
  - "2.1"
  - "2.0.0"
  - jruby-19mode
gemfiles:
  - gemfiles/ar42.gemfile
  - gemfiles/ar41.gemfile
  - gemfiles/ar40.gemfile
  - gemfiles/ar32.gemfile
env:
  - ADAPTER="postgresql"
  - ADAPTER="derby"
  - ADAPTER="sqlite3"
