language: ruby
sudo: false
cache: bundler
services:
  - postgresql
jdk:
  - openjdk8
rvm:
  - ruby-2.6
  - ruby-2.5
  - ruby-2.4
  - jruby
gemfile:
  - gemfiles/ar52.gemfile
  - gemfiles/ar51.gemfile
env:
  - JRUBY_OPTS="--dev --debug" ADAPTER="postgresql"
  - JRUBY_OPTS="--dev --debug" ADAPTER="sqlite3"
