language: ruby
sudo: false
rvm:
  - jruby-head
  - ruby-head
  - "2.2"
  - jruby-19mode
  - "2.1"
  - "2.0.0"
  - "1.9.3"
env:
  - AR_VERSION="~>4.2.1"
  - AR_VERSION="~>4.1.10"
  - AR_VERSION="~>4.0.13"
  - AR_VERSION="~>3.2.21"
