language: ruby
sudo: false
jdk:
  - oraclejdk8
before_install: gem query -i -n ^bundler$ >/dev/null || gem install bundler
rvm:
  - ruby-2.4.1
  - jruby-9.1.12.0
  - ruby-2.3.4
  - ruby-2.2.7
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/ar51.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar42.gemfile
  - gemfiles/ar32.gemfile
env:
  - JRUBY_OPTS="--dev --debug" ADAPTER="postgresql"
  - JRUBY_OPTS="--dev --debug" ADAPTER="derby"
  - JRUBY_OPTS="--dev --debug" ADAPTER="sqlite3"
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/ar42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ar32.gemfile
    - rvm: ruby-2.4.1
      gemfile: gemfiles/ar32.gemfile
