language: ruby
sudo: false
services:
  - postgresql
before_install: gem install bundler:1.17.2 # TODO(uwe): https://github.com/travis-ci/travis-ci/issues/9383
jdk:
  - openjdk8
rvm:
  - ruby-2.6.5
  - ruby-2.5.7
  - ruby-2.4.9
  - jruby-9.2.8.0
gemfile:
  - gemfiles/ar52.gemfile
  - gemfiles/ar51.gemfile
env:
  - JRUBY_OPTS="--dev --debug" ADAPTER="postgresql"
  - JRUBY_OPTS="--dev --debug" ADAPTER="sqlite3"
matrix:
  allow_failures:
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/ar52.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/ar51.gemfile
